project:
  type: website
  output-dir: docs   #execute-dir: project #- https://quarto.org/docs/projects/code-execution.html#working-dir
  preview:
    port: 4444
    browser: true
    watch-inputs: true
    navigate: true
  resources:
    - "recursos/"
    - "slides/slides_en_pdf.zip"
    - "slides/slides_en_html.zip"
   # - "recursos/mi_articulo_01.pdf"
   #  - "recursos/Qproj_01_eurovision.zip"
   #  - "recursos/Qproj_02_param-rep.zip"
    
website:
  #page-navigation: true
  title: "{{< var my_title_web >}}"
  favicon: imagenes/uv.jpeg
  site-url: "{{< var my_url_web >}}"
  repo-url: "{{< var my_url_repo_github >}}"
  #google-analytics: "G-XLVN8SCPEF"
  repo-actions: [source, issue]
  repo-branch: master  #- edit page in Github https://github.com/quarto-dev/quarto-cli/discussions/4826
  #open-graph: true #-https://quarto.org/docs/websites/website-tools.html#twitter-cards
  #twitter-card:
  #  creator: "@pjpv4444"
  #  card-style: summary_large_image
  navbar:
    pinned: true
    background: "#F1F3F4"   # "#F8F8F8"   # "#C0B9A0"  # "#e9e8f0"   #- color de R-ladies    # secondary
    collapse-below: lg
    logo: "imagenes/ababol_redondeado.png"
    #background: primary #- pink
    left: 
      - icon: house-door
        href: index.html
    right:
      - text: "Info"
        href: info.qmd 
      - text: "Materiales"
        href: materiales.qmd        
      - text: "Blog"
        href: blog.qmd  
        target: _blank
      - text: "Truquillos"
        href: blog_02.qmd 
        target: _blank
      - about.qmd
      # - icon: github
      #   href: https://github.com/perezp44
      # - icon: twitter
      #   href: https://twitter.com/pjpv4444
      - icon: envelope
        url: "mailto:pedro.j.perez@uv.es"
        
  page-footer:
    background: "#e9e8f0" 
    left: "{{< var my_anyo_web >}}"   #- sí, va entre comillas
    #center: "Hecho con [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/perezp44/intro.to.quarto.2025
      # - icon: twitter
      #   href: https://twitter.com/pjpv4444
      - icon: envelope
        url: "mailto:pedro.j.perez@uv.es"
      - text: <i class="ai ai-google-scholar" role="img"></i>
        href: https://scholar.google.de/citations?user=MFlgHdcAAAAJ&hl=en
      - text: <i class="ai ai-orcid" role="img"></i>
        href: https://orcid.org/0000-0001-9375-6330

format:
  html:
    page-layout: full
    #theme: ember.scss  #- de danielle Navarro(https://blog.djnavarro.net/posts/2022-04-20_porting-to-quarto/)
    theme: 
      - cosmo #sketchy #slate #- litera  superhero darkly
      - assets/ember.scss #- siempre estaba mal!!! assests/ember.scss
    #   - custom.scss
    css: 
      - assets/styles.css
    toc: true
    code-line-numbers: true
    code-copy: true
    code-overflow: wrap    #- {wrap, scroll}
    code-fold: show
    code-tools: false
    #code-summary: "Show the code"
    code-link: true
    
lang: es   #- {es, en}


# freeze computational output
# (see https://quarto.org/docs/projects/code-execution.html#freeze)
execute:
  freeze: true  # re-render only when source changes
  echo: true
  message: false
  warning: false
  eval: true
  cache: true
  
#editor: visual

embed-resources: true

highlight-style: monochrome

link-external-newwindow: true

#title-block-banner: true  #- {true, false, "#FFDDFF",  "image.jpg"}