::: {.callout-important icon="false"}
#### Tarea 1.1: Hemos de crear la carpeta que contendrá nuestro <mark>blog</mark>. 

**La carpeta la creará Quarto, pero tenemos 3 formas de hacerlo**:

<br>

###### A) Crear la carpeta (o Qproject) desde **RStudio**

-   En RStudio sigue la siguiente ruta de menús:   

    `File > New Project > New Directory >` <mark>Quarto Blog</mark>
    
-   Mejor si llamas a la carpeta:  `blog_prueba_00`

:::

<br>

::: {.fragment}
::: {.callout-warning icon="false"}
#### Extensión a la tarea 1.1: Se puede crear la carpeta de otras formas

<br>

###### B) Crear la carpeta desde la **Terminal**


- Has de ejecutar desde la Terminal:


  ```{bash}
  #| code-line-numbers: false
  #| eval: false
  quarto create-project blog_prueba_00 --type website --template blog         
  ```

<br>

###### C) Usando un Qproject ya creado con **RStudio Cloud**

- Tienes que ir [aquí](https://rstudio.cloud/content/4743159). Se abrirá Rstudio en el navegador con un Qproject llamado `blog_prueba_00`.

- Has de tener cuenta en [RStudio Cloud](https://rstudio.cloud/). Haz una copia permanente y trabaja sobre ella

<br>

De cualquiera de las 3 maneras **acabaremos teniendo una carpeta con todo o necesario para crear un blog**.
:::

:::